In [8]:
import pickle
import numpy as np

In [9]:
clf = pickle.load(open("clf.pkl",'rb'))
ohe = pickle.load(open("ohe.pkl",'rb'))
ohe_embarked= pickle.load(open("ohe_embarked.pkl",'rb'))



In [10]:
test_input = np.array(
                [1, 'male', 65.0, 0, 0, 26.55, 'S'],
                dtype=object
            ).reshape(1,7)

test_input

array([[1, 'male', 65.0, 0, 0, 26.55, 'S']], dtype=object)

In [11]:
test_sex = ohe.transform(test_input[:,1].reshape(1,1))

test_sex

/home/mypc/Desktop/180-Days-of-Code/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [12]:
test_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_embarked

array([[0., 0., 1.]])

In [14]:
test_data = np.concatenate((test_input[:,[0,2,4,5]],test_input[:,[3]],test_sex,test_embarked),axis=1)
test_data

array([[1, 65.0, 0, 26.55, 0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [16]:
test_data.shape

(1, 10)

In [18]:
clf.predict(test_data)

array([0])